# Generated by Django 5.0.9 on 2024-10-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0012_osfp_instance_vrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticroute',
            name='route_tag',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
