# Generated by Django 5.0.9 on 2024-10-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0013_staticroute_route_tag_alter_next_hop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ospfinstance',
            name='process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
