# Generated by Django 5.0.9 on 2024-10-27 07:36

import django.db.models.deletion
import ipam.fields
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_routing', '0014_alter_ospfinstance_process_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSPFNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('network', ipam.fields.IPNetworkField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='netbox_routing.ospfarea')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='netbox_routing.ospfinstance')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'OSPF Network Statements',
                'ordering': ('network', 'instance', 'area'),
            },
        ),
        migrations.AddConstraint(
            model_name='ospfnetworks',
            constraint=models.UniqueConstraint(fields=('network', 'instance', 'area'), name='netbox_routing_ospfnetworks_unique_network'),
        ),
    ]
