# Generated by Django 5.0.9 on 2024-10-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0014_alter_staticroute_next_hop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticroute',
            name='next_hop',
            field=models.CharField(max_length=15),
        ),
    ]
