# Generated by Django 5.0.9 on 2024-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('extras', '0121_customfield_related_object_filter'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_routing', '0015_ospfnetworks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ospfinstance',
            options={'ordering': ('router_id', 'name', 'device', 'vrf')},
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(fields=('router_id', 'name', 'device'), name='netbox_routing_ospfinstance_unique_ospfinstance'),
        ),
    ]
