# Generated by Django 5.0.9 on 2024-10-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0016_alter_ospfinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ospfinstance',
            options={'ordering': (('router_id', 'name', 'device', 'vrf'),)},
        ),
    ]
