# Generated by Django 5.0.9 on 2024-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('extras', '0121_customfield_related_object_filter'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_routing', '0018_alter_ospfinstance_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ospfinstance',
            name='netbox_routing_ospfinstance_unique_ospfinstance',
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(fields=('router_id', 'device'), name='netbox_routing_ospfinstance_unique_router_id_device'),
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(fields=('router_id', 'vrf'), name='netbox_routing_ospfinstance_unique_router_id_vrf'),
        ),
    ]
