# Generated by Django 5.0.9 on 2024-10-28 17:44

import django.db.models.deletion
import ipam.fields
import netbox_routing.fields.ip
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

   
    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('extras', '0121_customfield_related_object_filter'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_routing', '0013_staticroute_route_tag_alter_next_hop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ospfinstance',
            name='process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OSPFNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('network', ipam.fields.IPNetworkField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='netbox_routing.ospfarea')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='netbox_routing.ospfinstance')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'OSPF Network Statements',
                'ordering': ('network', 'instance', 'area'),
            },
        ),
        migrations.AddConstraint(
            model_name='ospfnetworks',
            constraint=models.UniqueConstraint(fields=('network', 'instance', 'area'), name='netbox_routing_ospfnetworks_unique_network'),
        ),
        migrations.AlterModelOptions(
            name='ospfinstance',
            options={'ordering': ('router_id', 'name', 'device', 'vrf')},
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(fields=('router_id', 'name', 'device'), name='netbox_routing_ospfinstance_unique_ospfinstance'),
        ),
        migrations.AlterModelOptions(
            name='ospfinstance',
            options={'ordering': ('router_id', 'name', 'device', 'vrf')},
        ),
        migrations.RemoveConstraint(
            model_name='ospfinstance',
            name='netbox_routing_ospfinstance_unique_ospfinstance',
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(fields=('router_id', 'device'), name='netbox_routing_ospfinstance_unique_router_id_device'),
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(fields=('router_id', 'vrf'), name='netbox_routing_ospfinstance_unique_router_id_vrf'),
        ),
        migrations.AlterField(
            model_name='ospfinstance',
            name='router_id',
            field=netbox_routing.fields.ip.IPAddressField(),
        ),
        migrations.RemoveConstraint(
            model_name='ospfinstance',
            name='netbox_routing_ospfinstance_unique_router_id_device',
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(fields=('router_id', 'device', 'vrf'), name='netbox_routing_ospfinstance_unique_router_id_device'),
        ),
    ]
