# Generated by Django 5.0.9 on 2024-11-04 21:08

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('extras', '0121_customfield_related_object_filter'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_routing', '0015_ospfinterface_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISISInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('isis_type', models.IntegerField(default=2)),
                ('net', models.CharField(max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isis_instances', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isis_instances', to='ipam.vrf')),
            ],
            options={
                'verbose_name': 'ISIS Instance',
                'ordering': ('name', 'device', 'vrf', 'net'),
            },
        ),
        migrations.CreateModel(
            name='ISISInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('metric', models.SmallIntegerField(blank=True, null=True)),
                ('passive', models.BooleanField(blank=True, null=True)),
                ('bfd', models.BooleanField(blank=True, null=True)),
                ('authentication', models.CharField(blank=True, max_length=50, null=True)),
                ('passphrase', models.CharField(blank=True, max_length=200, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='netbox_routing.isisinstance')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isis_interfaces', to='dcim.interface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ISIS Interface',
                'ordering': ('instance', 'interface'),
            },
        ),
        migrations.AddConstraint(
            model_name='isisinstance',
            constraint=models.UniqueConstraint(fields=('name', 'device', 'net'), name='netbox_routing_isisinstance_unique_name_device'),
        ),
        migrations.AddConstraint(
            model_name='isisinterface',
            constraint=models.UniqueConstraint(fields=('interface',), name='netbox_routing_isisinterface_unique_interface'),
        ),
    ]
