# Generated by Django 5.0.9 on 2024-11-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('extras', '0121_customfield_related_object_filter'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_routing', '0016_isisinstance_isisinterface_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='isisinstance',
            name='netbox_routing_isisinstance_unique_name_device',
        ),
        migrations.AddConstraint(
            model_name='isisinstance',
            constraint=models.UniqueConstraint(fields=('net',), name='netbox_routing_isisinstance_unique_net'),
        ),
        migrations.AddConstraint(
            model_name='isisinstance',
            constraint=models.UniqueConstraint(fields=('name', 'device'), name='netbox_routing_isisinstance_unique_name_device'),
        ),
    ]
